set t_Co=256
colorscheme greenvision
set nu
set expandtab
set tabstop=4

execute pathogen#infect()
syntax on
filetype plugin indent on
" also, if you're on bt5, kali, ubuntu... GNOME, make sure to
" hit Profile Prefrences in terminal 
" > Colors > Palette > Built-in Schemes > XTERM
" otherwise they interfere.
